version: 1.0.{build}
configuration: Release

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - feature/* #these I want to tag as "pre-release"

skip_non_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: 1.0.0.0
  file_version: '{version}'
  informational_version: '{version}'

nuget:
  project_feed: true
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

after_build:
  - cmd: dotnet pack src\ --include-symbols --configuration %CONFIGURATION% --no-build --output ..\nupkgs /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

build_script:
  - cmd: dotnet build --configuration %CONFIGURATION%

artifacts:
  - path: nupkgs\*.nupkg
