version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:  
- ps: .\Build.ps1

artifacts:
- path: .\src\artifacts\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: /f9zserPJzsJ8FuS6VxDXFs9Xjacu3mJlCP1LpE60gkc9rqPr33mAz1BUGegXcTF
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  skip_symbols: true
  api_key:
    secure: /f9zserPJzsJ8FuS6VxDXFs9Xjacu3mJlCP1LpE60gkc9rqPr33mAz1BUGegXcTF
  on:
    branch: /feature.*/



# for:

# # configuration for "master" branch
# -
#   branches:
#     only:
#       - master
#   configuration: Release
#   deploy:
#   - provider: NuGet
#     api_key:
#       secure: /f9zserPJzsJ8FuS6VxDXFs9Xjacu3mJlCP1LpE60gkc9rqPr33mAz1BUGegXcTF
#     artifact: /.*\.nupkg/

# # configuration for all branches starting from "feature"
# -
#   branches:
#     only:
#       - /feature.*/
#   configuration: Debug
#   deploy:
#   - provider: NuGet
#     prerelease: true
#     api_key:
#       secure: /f9zserPJzsJ8FuS6VxDXFs9Xjacu3mJlCP1LpE60gkc9rqPr33mAz1BUGegXcTF
#     artifact: /.*\.nupkg/