skip_tags: true
image: Visual Studio 2019

install:
  - cmd: choco install gitversion.portable --version 4.0.0 -y

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: detailed

build_script:
- cmd: dotnet restore ./SlugHub.sln --disable-parallel
- cmd: dotnet build ./SlugHub.sln -c Release --disable-parallel
- cmd: dotnet pack ./SlugHub.sln -c Release --output %APPVEYOR_BUILD_FOLDER%/artifacts/

test_script:
- cmd: dotnet test ./tests/SlugHub.Tests/SlugHub.Tests.csproj

artifacts:
- path: artifacts/*